### ISSUE TITLE
Lab vs Notebook

### ISSUE THREAD

**Issue by kmpaul** [pangeo-data/pangeo-tutorial-sea-2018#4]
@jhamman Some of the diagnostic tools for the local schedulers require inline javascript, which is disabled for security reasons in jupyter lab.  To cover that material, I will need the to use notebooks, instead.  I'm fine just saying that they should use notebooks for the dask section, but do you want to tell them to use notebooks for the whole tutorial?

**Comment by jhamman** [comment]
@kmpaul - I think this should work now. Can you try: 

```jupyter nbextension enable --py widgetsnbextension``` from your environment that runs jupyter?

**Comment by kmpaul** [comment]
Just tried it.  I still get:

![screen shot 2018-04-03 at 7 44 39 am](https://user-images.githubusercontent.com/11411331/38253072-f4570382-3712-11e8-9abe-a78540f38067.png)

**Comment by kmpaul** [comment]
I think I might have figured it out from here bokeh/bokeh#6700.  Looks like you need to do:

    conda install nodejs
    jupyter labextension install jupyterlab_bokeh

So, that requires adding `nodejs` to the environment and having them run the labextension install.

I can add this to the `setup.md`, if you approve.

**Comment by jhamman** [comment]
@kmpaul - If that works, yes, go ahead and add that to the `environment.yml` and the setup instructions?

@mrocklin - do you have any other guidance in this area?

**Comment by mrocklin** [comment]
Nothing from me.  The documentation in https://github.com/bokeh/jupyterlab_bokeh seems similar.  

You might reach out to Bokeh devs for more information.  I think that they prefer interactions on gitter at https://gitter.im/bokeh/bokeh.

**Comment by kmpaul** [comment]
Great!  Thanks @jhamman and @mrocklin!
